### ISSUE TITLE
Hard-coded Patient FHIR birthday

### ISSUE THREAD

**Issue by ericpan64** [omoponfhir/omoponfhir-omopv5-dstu2-mapping#3]
When constructing the FHIR resource from OMOP as-is, a birthday/year/month/day of "1" is assumed if it is not present in the database:
https://github.com/omoponfhir/omoponfhir-omopv5-dstu2-mapping/blob/0f2de24e159f13d7bea888acccd273cda87b8b5f/src/main/java/edu/gatech/chai/omoponfhir/omopv5/dstu2/mapping/OmopPatient.java#L260-L268

This is problematic, especially because month/day are _optional_ in the OMOP cdm schema. This can lead to patient matching issues in downstream systems for cases when a patient's month/day are not available, as birthday is a common piece of data validation. 

birthDate is not a required field from the [FHIR DSTU2 schema](https://www.hl7.org/fhir/DSTU2/Patient.html), I think it's better to omit cases when month/date/year aren't available instead of sending incorrect data

**Comment by myungchoi** [comment]
Year of birth is required in omop. So you should have something for year. For Date class, as far as I know, you need to set something for month and day if those are null.

I am welcomed to your suggestion if there is a way that you can only set year when month and day are null.

If year is null, which should not happen, yes we can skip the birthdate set. Good catch. We will update it in our next release.
